### ISSUE TITLE
ImportError: No module named flowEntrys

### ISSUE THREAD

**Issue by ncme** [lsinfo3/BDD-mininet#1]
Hi folks,
when i tried running your code for the first time i got this error:  

``` python
Exception ImportError: No module named flowEntrys
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 678, in run_with_paths
    self.load_step_definitions()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 658, in load_step_definitions
    exec_file(os.path.join(path, name), step_module_globals)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "steps/helper.py", line 3, in <module>
    from flowEntrys import FlowTable
ImportError: No module named flowEntrys
```

Seems to be just a typo in your import statement. Changing `flowEntrys` to `FlowEntrys` resolved the error for me.

**Comment by JayBeeCee** [comment]
Thank you for your message, I fixed that typo!
