### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'onosRest'

### ISSUE THREAD

**Issue by ncme** [lsinfo3/BDD-mininet#2]
Hi folks,
after fixing issue #1 and running your code against the default controller with `behave --tags OVS` i got the following error:  

``` python
Exception AttributeError: 'Context' object has no attribute 'onosRest'
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 919, in run
    runner.run_hook('after_scenario', runner.context, self)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "environment.py", line 78, in after_scenario
    context.onosRest.removeOnosIntens()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 214, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'onosRest'
```

Since I was not using ONOS I was able to make it work again by commenting out the affected line. It just seems you are missing the check if an onos controller is present before calling `onosRest` here.

**Comment by JayBeeCee** [comment]
Thank you for your message! I fixed that issue. It should not throw an error anymore!
